version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.82"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: popgetter-py
      extra_requirements:
        - docs
