[package]
name = "popgetter_cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "popgetter"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version="1.0"}
tokio = { version = "1.30.0", features = ["full"] }
clap = { version = "4.5.0", features = ["derive"] }
polars = {version ="0.33.2", features=["lazy","aws", "parquet"]}
typify = "0.0.16"
chrono = "0.4.37"
reqwest = {version = "0.12.3", features = ["json"]}
<<<<<<< HEAD
strum = "0.26"
strum_macros = "0.26"
enum_dispatch = "0.3"
=======
flatgeobuf = "4.1.0"
geozero = {version = "0.12.0", features= []} 
httpmock = "0.7.0-rc.1"
>>>>>>> fb462fe (First pass at function to retrive features from a flatgeobuff)
