[package]
name = "popgetter-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
langchain-rust = { version = "4.6.0", features = ["qdrant", "qdrant-client"] }
polars.workspace = true
popgetter = { path = "../popgetter" }
serde_json.workspace = true
tokio.workspace = true
