[package]
name = "popgetter-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
itertools.workspace = true
langchain-rust = { version = "4.6.0", features = ["qdrant", "qdrant-client"] }
polars.workspace = true
popgetter = { path = "../popgetter" }
rand = "0.8.5"
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
tokio.workspace = true
